### ISSUE TITLE
Command::before_unfreeze should return &mut self to allow chaining in builder pattern

### ISSUE THREAD

**Issue by joshtriplett** [tailhook/unshare#15]
Most methods of `Command` return `self`, to allow chaining them together in the builder pattern. However, `Command::before_unfreeze` doesn't return anything. Please consider having it (and `before_exec`) return `self` as well.

**Comment by tailhook** [comment]
Nice catch. Also, since this is technically a breaking change, we should also make `before_exec` unsafe like stdlib did. Do you want to make a PR?

**Comment by joshtriplett** [comment]
https://github.com/tailhook/unshare/pull/16

**Comment by tailhook** [comment]
Done!
