### ISSUE TITLE
ping: is this project active?

### ISSUE THREAD

**Issue by sjames** [tailhook/unshare#17]
Hi,
I'm very interested in this project. I have tried it out and made some slight changes in my fork at https://github.com/sjames/unshare.  
I'm posting this to check if someone is listening and whether they may be interested in a pull request.

I'm also curious to learn where this library is being used. 

Thanks and regards,
Sojan

**Comment by tailhook** [comment]
Hi! This is a tough question. While I'm still using the library in the tools I'm using daily. Both of them are quite in maintenance mode. I'm interested in `unshare` going forward, but I'm not sure I'll have enough time to review large changes.

**Comment by sjames** [comment]
Thanks for the reply. I'll keep this in mind.  The changes are quite small.
